name: JSON Generate

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: codeGen
        run: |
          yarn
          yarn codegen

      - name: Push To main
        working-directory: lib # 指定下面指令运行的目录
        run: |
          git init
          git checkout -b main
          git add -A

          git -c user.name='WKlili' -c user.email='18136225579@163.com' commit -m 'update'

          git remote add origin https://${{ github.TOKEN }}@github.com:WhiteMatrixTech/micro-mega-copywrite.git

          git push origin main -f -q

